'use client';

import { useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
import { createClient } from '../lib/supabase/client';

const columns=[['sent_to_kitchen','New'],['preparing','Preparing'],['ready','Ready'],['served','Served']];
export default function KitchenPage(){
 const supabase=createClient();const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setLoading(true);const {data,error:e}=await supabase.from('orders').select('id,order_number,order_type,table_id,customer_name,status,created_at,order_items(id,product_name,quantity,notes)').in('status',columns.map(c=>c[0])).order('created_at',{ascending:true});if(e)setError(e.message);else setOrders(data||[]);setLoading(false)}
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 async function advance(order){const next={sent_to_kitchen:'preparing',preparing:'ready',ready:'served',served:'completed'}[order.status];const {error:e}=await supabase.from('orders').update({status:next,completed_at:next==='completed'?new Date().toISOString():null}).eq('id',order.id);if(e)setError(e.message);else load()}
 return <AppShell><main className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Restaurant operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Kitchen display</h1><p className="mt-2 text-sm text-[#748074]">Orders refresh automatically. Move tickets through the kitchen as they are prepared.</p></div><button onClick={load} className="rounded-xl border border-[#d9e1d4] bg-white px-4 py-3 text-sm font-bold">Refresh</button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{loading?<div className="py-16 text-center text-sm text-[#758075]">Loading kitchen…</div>:<div className="mt-8 grid gap-4 lg:grid-cols-4">{columns.map(([status,label])=><section key={status} className="rounded-2xl bg-[#edf1eb] p-3"><div className="flex items-center justify-between px-2 py-2"><h2 className="font-bold">{label}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-bold">{orders.filter(o=>o.status===status).length}</span></div><div className="space-y-3">{orders.filter(o=>o.status===status).map(o=><article key={o.id} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><b>#{o.order_number}</b><span className="text-xs text-[#758075]">{new Date(o.created_at).toLocaleTimeString('en-KE',{hour:'2-digit',minute:'2-digit'})}</span></div><p className="mt-2 text-sm font-semibold">{o.customer_name||o.order_type.replace('_',' ')}</p><div className="mt-3 divide-y divide-[#edf0eb]">{(o.order_items||[]).map(i=><div key={i.id} className="flex justify-between py-2 text-sm"><span>{i.product_name}</span><b>×{i.quantity}</b></div>)}</div><button onClick={()=>advance(o)} className="mt-3 w-full rounded-xl bg-[#335f3b] py-2.5 text-sm font-bold text-white">{status==='served'?'Complete ticket':`Mark ${columns.find(c=>c[0]===({'sent_to_kitchen':'preparing','preparing':'ready','ready':'served'}[status]))?.[1]||'next'}`}</button></article>)}</div></section>)}</div>}</main></AppShell>
}
