'use client';

import { useEffect, useMemo, useState } from 'react';
import AppShell from '../components/AppShell';
import { formatMoney, getOrders } from '../lib/pos';

export default function DailySummary() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { getOrders().then(setOrders).catch(e => setError(e.message || 'Unable to load summary.')).finally(() => setLoading(false)); }, []);
  const today = useMemo(() => orders.filter(o => new Date(o.created_at).toDateString() === new Date().toDateString()), [orders]);
  const stats = useMemo(() => ({ total: today.reduce((sum, o) => sum + Number(o.total_amount || 0), 0), cash: today.filter(o => o.payments?.some(p => p.method === 'cash' && p.status === 'confirmed')).reduce((sum, o) => sum + Number(o.total_amount || 0), 0), mobile: today.filter(o => o.payments?.some(p => ['mpesa','airtel_money'].includes(p.method) && p.status === 'confirmed')).reduce((sum, o) => sum + Number(o.total_amount || 0), 0), pending: today.filter(o => o.payment_status !== 'paid').length, cancelled: today.filter(o => ['cancelled','voided'].includes(o.status)).length }), [today]);
  return <AppShell><main className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><p className="eyebrow">Daily performance</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Daily summary</h1><p className="mt-2 text-sm text-[#718071]">A live view of today&apos;s sales, payments and order activity.</p>{loading ? <div className="mt-8 panel p-10 text-center text-sm text-[#758075]">Loading summary…</div> : error ? <div className="mt-8 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Stat label="Total orders" value={String(today.length)} /><Stat label="Total revenue" value={formatMoney(stats.total)} strong /><Stat label="Cash" value={formatMoney(stats.cash)} /><Stat label="Mobile money" value={formatMoney(stats.mobile)} /><Stat label="Pending verification" value={String(stats.pending)} amber /><Stat label="Cancelled / voided" value={String(stats.cancelled)} /></section><section className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="panel p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Payment breakdown</h2><p className="mt-1 text-sm text-[#758075]">Confirmed payment value by method</p></div><span className="text-xs font-bold text-[#71816d]">Today</span></div><div className="mt-7 space-y-6"><Bar label="Cash" value={stats.cash} total={stats.total} /><Bar label="Mobile money" value={stats.mobile} total={stats.total} /></div></div><div className="panel p-5"><h2 className="font-bold">Operations snapshot</h2><p className="mt-1 text-sm text-[#758075]">Current order status distribution</p><div className="mt-5 divide-y divide-[#edf0ea]">{['open','confirmed','preparing','ready','served','completed','cancelled','voided'].map(status => { const count = today.filter(o => o.status === status).length; return count ? <div key={status} className="flex items-center justify-between py-3"><span className="font-semibold capitalize">{status}</span><b>{count}</b></div> : null; })}{!today.length && <p className="py-8 text-center text-sm text-[#758075]">No activity recorded yet.</p>}</div></div></section></>}</main></AppShell>;
}
function Stat({ label, value, amber, strong }) { return <div className={`panel p-5 ${amber ? 'border-[#efdca6] bg-[#fffdf7]' : ''}`}><p className="text-sm text-[#748074]">{label}</p><p className={`mt-2 text-2xl font-bold ${strong ? 'text-[#315f30]' : ''}`}>{value}</p></div>; }
function Bar({ label, value, total }) { const percent = total ? Math.round((value / total) * 100) : 0; return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-[#667566]">{formatMoney(value)} · {percent}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-[#edf1e9]"><div className="h-full rounded-full bg-[#3f793d]" style={{ width: `${percent}%` }} /></div></div>; }
