'use client';

import { useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
import { createClient } from '../lib/supabase/client';

const statuses = ['available','occupied','reserved','blocked'];
const tone = { available:'bg-[#e8f3e4] text-[#397034]', occupied:'bg-[#fff0ee] text-[#a64840]', reserved:'bg-[#fff4dc] text-[#926718]', blocked:'bg-[#eef1ed] text-[#5d6d5f]' };

export default function TablesPage(){
 const supabase=createClient(); const [tables,setTables]=useState([]); const [branches,setBranches]=useState([]); const [branchId,setBranchId]=useState(''); const [form,setForm]=useState({name:'',capacity:2,area:''}); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);const {data:m,error:e}=await supabase.from('memberships').select('branch_id,branches(id,name,code)').eq('status','active').not('branch_id','is',null);if(e){setError(e.message);setLoading(false);return}const bs=(m||[]).map(x=>x.branches).filter(Boolean);setBranches(bs);const b=branchId||bs[0]?.id||'';if(!branchId&&b)setBranchId(b);const {data,error:te}=await supabase.from('restaurant_tables').select('*').eq('branch_id',b).eq('is_active',true).order('sort_order').order('name');if(te)setError(te.message);else setTables(data||[]);setLoading(false)}
 useEffect(()=>{load()},[branchId]);
 async function add(e){e.preventDefault();setError('');const {data:m}=await supabase.from('memberships').select('organization_id').eq('branch_id',branchId).eq('status','active').limit(1).single();if(!m){setError('No active branch membership.');return}const {error:e2}=await supabase.from('restaurant_tables').insert({organization_id:m.organization_id,branch_id:branchId,name:form.name.trim(),capacity:Number(form.capacity),area:form.area.trim()||null});if(e2)setError(e2.message);else{setForm({name:'',capacity:2,area:''});setShow(false);load()}}
 async function setStatus(table,status){const {error:e}=await supabase.from('restaurant_tables').update({status}).eq('id',table.id);if(e)setError(e.message);else load()}
 return <AppShell><main className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Restaurant floor</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Tables</h1><p className="mt-2 text-sm text-[#748074]">See table availability at a glance and keep the dining floor synchronized with the POS.</p></div><button onClick={()=>setShow(!show)} className="rounded-xl bg-[#3c763a] px-4 py-3 text-sm font-bold text-white">{show?'Close':'+ Add table'}</button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{show&&<form onSubmit={add} className="panel mt-6 grid gap-4 p-5 sm:grid-cols-3"><Field label="Table name" value={form.name} onChange={v=>setForm({...form,name:v})} required/><Field label="Capacity" type="number" value={form.capacity} onChange={v=>setForm({...form,capacity:v})} required/><Field label="Area / section" value={form.area} onChange={v=>setForm({...form,area:v})}/><button className="rounded-xl bg-[#2f5b3c] py-3 font-bold text-white sm:col-span-3">Save table</button></form>}<div className="mt-8"><select value={branchId} onChange={e=>setBranchId(e.target.value)} className="rounded-xl border border-[#dfe6da] bg-white px-3 py-2.5 text-sm">{branches.map(b=><option key={b.id} value={b.id}>{b.name} ({b.code})</option>)}</select></div>{loading?<div className="py-16 text-center text-sm text-[#758075]">Loading tables…</div>:<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{tables.map(t=><article key={t.id} className="panel p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">{t.name}</h2><p className="mt-1 text-sm text-[#748074]">Seats {t.capacity}{t.area?` · ${t.area}`:''}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${tone[t.status]}`}>{t.status.replace('_',' ')}</span></div><div className="mt-5 grid grid-cols-2 gap-2">{statuses.filter(s=>s!==t.status).map(s=><button key={s} onClick={()=>setStatus(t,s)} className="rounded-lg border border-[#dfe6da] px-2 py-2 text-xs font-bold capitalize">{s.replace('_',' ')}</button>)}</div></article>)}{!tables.length&&<div className="panel col-span-full p-12 text-center text-sm text-[#758075]">No tables configured for this branch yet.</div>}</div>}</main></AppShell>
}
function Field({label,value,onChange,type='text',required}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input required={required} type={type} min={type==='number'?1:undefined} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[#d9e1d4] px-4 py-3 outline-none focus:border-[#557c45]"/></label>}
